version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 80:80
    volumes:
      - ./:/var/www/html/

  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: user_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: